config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get "users/sign_out"

resources :expenses
post "expenses/new"
post "expenses/delete"
post "expenses/show"

resources :accounts
post "accounts/new"

    

   root to: "accounts#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
	has_and_belongs_to_many :users, :join_table => 'users_accounts'
	has_many :expenses

	def total_expenses
		total = 0
		self.expenses.each do |e|
			total += e.amount
		end
		return total 
	end


# Account.first.total_expenses


end

app/models/expense.rb
class Expense < ActiveRecord::Base
belongs_to :user
belongs_to :account
end

class Money
Money::Currency

def major_currencies(hash)
  hash.inject([]) do |array, (id, attributes)|
    priority = attributes[:priority]
    if priority && priority < 10
      array[priority] ||= []
      array[priority] << id
    end
    array
  end.compact.flatten
end


end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :expenses
	has_and_belongs_to_many :accounts, :join_table => 'users_accounts'

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         def expenses_for_account(account)
         	total = 0
         	Expense.where(:account_id => account.id, :user_id => self.id).each do |e|
         		total += e.amount
         	end
         	return total
         end
end

app/models/users_account.rb
class UsersAccount < ActiveRecord::Base
	belongs_to :user

	validates_uniqueness_of :user_id, :scope => :account_id
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController


    def index
        @accounts = Account.all

    end


	def show
    	@account = Account.find(params[:id])
	end

	def new
		@account = Account.new
		@account.save
		redirect_to accounts_path
	end
	
	def create
		@account = Account.new(create_params)
		@account.save
		redirect_to accounts_path
	end


	def edit
		@account = Account.find(params[:id])
	end

	def update
		@account = Account.find(params[:id])
		if params[:add_current_user] == 'true'
			@user = User.find(current_user.id)
			ua = UsersAccount.new(:user_id => @user.id, :account_id => @account.id)
			if ua.save
				redirect_to account_path(@account), notice: 'User Added Successfully'
			else
				redirect_to accounts_path, notice: 'Duplicate User Id'
			end
		else
			if @account.update(account_params)
				redirect_to account_path
			else
				render 'edit'
			end
		end
	end

	def destroy
		@account = Account.find(params[:id])
    	@account.destroy
    	respond_to do |format|
     		format.html { redirect_to accounts_path, notice: 'Account was successfully destroyed.' }
      		format.json { head :no_content }
    	end
 	end

 	def delete
 		@account = Account.find(params[:id])
    	@account.delete
 	end	

	private
	def account_params
		params.require(:account).permit(:expense_id, :user_id)
	end

	


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController

	def index
		@expenses = Expense.all.where(:account_id => current_user.accounts.first.id)
		@accounts = current_user.accounts
	end

	def new
		@expense = Expense.new
		@expense.user_id = current_user.id
		@expense.save
	end
	
	def create
		@expense = Expense.new
		@expense.user_id = current_user.id
		@expense.save
		redirect_to expenses_path
	end

	def show
		@expense = Expense.find(params[:id])
	end


	def edit
		@expense = Expense.find(params[:id])
	end

	def update
		@expense = Expense.find(params[:id])
		if @expense.update(expense_params)
			redirect_to expenses_path
		else
			render 'edit'
		end
	end

	def destroy
		@expense = Expense.find(params[:id])
    	@expense.destroy
    	respond_to do |format|
     		format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      		format.json { head :no_content }
    	end
 	end

 	def delete
 		@expense = Expense.find(params[:id])
 		@expense.delete
 	end	


	private
	def expense_params
		params.require(:expense).permit(:item, :amount, :category, :account_id, :user_id)
	end


end

app/controllers/users_accounts_controller.rb
class UsersAccountsController < ApplicationController
end

app/controllers/users_controller.rb
# class UsersController < ApplicationController
# 	before_action :authenticate_user!


# 	def index
#         @users = user_id.all
#     end


# 	def show
#     	# @user = UsersController.find(params[:id])
# 	end

# 	def new
# 		@user = User.new
# 	end
	
# 	def create
# 		@user = User.new(create_params)
# 		@user.save
# 		redirect_to users_path
# 	end

# 	def edit
# 		@user = User.find(params[:id])
# 	end

# 	def update
# 		@user = User.find(params[:id])
# 		if @user.update(user_params)
# 			redirect_to user_path
# 		else
# 			render 'edit'
# 		end
# 	end

# 	def destroy
# 		@user = User.find(params[:id])
#     	@user.destroy
#     	respond_to do |format|
#      		format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
#       		format.json { head :no_content }
#     	end
#  	end

# 	private
# 	def create_params
# 		params.require(:account).permit(:expense_id, :user_id)
# 	end



# end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def show_me_money
		'$$$'
	end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_accounts_helper.rb
module UsersAccountsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accounts/_form.html.erb
<%= form_for [@account], :html => {:multipart => true} do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">    

    <div class="field">
      <%= f.label :account_id %><br>

    </div>

   </form>
<% end %>

   

app/views/accounts/delete.html.erb
<p>delete</p>


<%= render 'form' %>

<%= link_to 'Show', @accounts %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>


<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<div class="page-header">
   <h1>Go Dutch
      <small>and travel the world!</small>
   </h1>
</div>



<h2>Create account</h2>

<%= button_to "New account", new_account_path %>

<h2>Join account</h2>


<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Account</th>
            <th>Join</th>

    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.id %></td>
        <%= form_for account do |f| %>
          <%= hidden_field_tag :add_current_user, true %>
          <td><%= f.submit 'Join Account' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>Allready joined an account?</h2>
<%= button_to "New expense", new_expense_path %> 

<br>

<br>



  <div class="panel-footer">&copy; BubblePoint 2014</div>

app/views/accounts/new.html.erb
<%= form_for :account do |f| %>

   <p>
    <%= f.label :account %><br>
    <%= f.number_field :account %>
   
  </p>
 
  <p>
    <%= f.submit %>
  </p>


<% end %>


<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<h2>Account</h2>
  <%= @account.id %>

<h2>User</h2>  
   <% @account.users.each do |u| %>
   <%= u.email %>
   <% end %>

<br>
<br>


<%= button_to'See expenses', expenses_path %>

app/views/expenses/_form.html.erb
<%= form_for [@expense], :html => {:multipart => true} do |f| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
  

    <div class="field">
      <%= f.label :item %><br>
      <%= f.text_field :item %>
    </div>

    <div class="field">
      <%= f.label :amount %><br>
      <%= f.text_field :amount, :placeholder=>"$" %>
    </div>

    <div class="field">
      <%= f.label :category %> <br>
      <%= f.select(:category, options_for_select([['Accomodation', 1], ['Transport', 2], ['Food and Drinks', 3], ['Entertainment', 4]]), {class: "form-control"}) %>
    </div>

    </div>

  
    <div class="field">
      <%= f.label :created_at %><br>
      <%= f.text_field :created_at %>
    </div>

   

    <div class="field">
      <%= f.label :account_id %><br>
      <%= f.select :account_id, Account.all.map { |c| [c.id, c.id] } %>
    </div>
  

  <div class="actions">
    <%= f.submit %><br>
  </div>
</form>
<br>
<% end %>



 

app/views/expenses/delete.html.erb
<h1>Delete expense</h1>


<%= render 'form' %>

<%= link_to 'Show', @expenses %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/edit.html.erb
	<%= render 'form' %>

	<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<h1>New expense</h1>

<%= button_to "New expense", new_expense_path %> 

<h2>All expenses</h2>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Item</th>
      <th>Amount</th>
      <th>Category</th>
      <th>Date</th>
      <th>User#</th>
      <th>Account#</th>
    </tr>
  </thead>

  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense.item %></td>
        <td> € <%= expense.amount %></td>
        <td><%= expense.category %></td>
        <td><%= expense.created_at %></td>
        <% if expense.user_id.present? %>
        <td><%= User.find(expense.user_id).email %></td>
        <% else %>
        <td></td>
        <% end %>
        <td><%= expense.account_id %></td>
        <td><%= button_to 'Show', expense, :method => :get %></td>
        <td><%= button_to 'Edit', edit_expense_path(expense), :method => :get %></td>
        <td><%= button_to 'Delete', expense, :method => :get , method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<% @accounts.each do |a| %> 

<h2>Total expenses</h2>
<h3>  €  <%= a.total_expenses %></h3>

<h2>Expenses per user</h2>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>User#</th>
      <th>Total amount</th>
    </tr>
  </thead>

 <tbody>
    <% a.users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td> € <%= user.expenses_for_account(a) %></td>
      </tr>
    <% end %>
  </tbody>




<% end %>


 

app/views/expenses/new.html.erb
<h1>New expense</h1>

<%= render 'form' %>


<%= link_to 'Show', @expenses %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<h2>Expense</h2>
  <%= @expense.id %>


<p>
  <strong>Item:</strong>
  <%= @expense.item %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @expense.amount %>
</p>

<p>
  <strong>Category:</strong>
  <%= @expense.category %>
</p>

<p>
  <strong>Date:</strong>
  <%= @expense.created_at %>
</p>

<p>
  <strong>User:</strong>
  <%= @expense.user_id %>
</p>

<p>
  <strong>Account:</strong>
  <%= @expense.account_id %>
</p>

  


   	 
   	 <%= link_to 'Back', expenses_path %>



   
  

app/views/expenses/update.html.erb
	<%= render 'form' %>

	<%= link_to 'Back', expenses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "GoDutch" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

   

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="http://gaaas.herokuapp.com">GoDutch</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Login", new_user_session_path  %></li>
            <li><%= link_to "Logout", destroy_user_session_path, :method => :delete  %></li>
            <li><%= link_to "Signup", new_user_registration_path %></li>
          </ul>
        </div>
      </div>
    </div>
</div>
 <div class="jumbotron">
    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>

        </div><!--/span-->
      </div><!--/row-->


<div class="footer">
    


    </div> <!-- /container -->

  </body>
</html>

app/views/users/index.html.erb
<h1>Create/join account</h1>
 
<%= show_me_money %>

 
<%#= link_to "New account", new_account_path %>